#!/bin/bash -x
OPENVIDU_RECORDING_UBUNTU_VERSION=$1
OPENVIDU_RECORDING_CHROME_VERSION=$2
OPENVIDU_RECORDING_DOCKER_IMAGE=$3
docker build --network=host --force-rm \
    --build-arg CHROME_VERSION="$OPENVIDU_RECORDING_CHROME_VERSION" \
    -f $OPENVIDU_RECORDING_UBUNTU_VERSION.Dockerfile \
    -t $OPENVIDU_RECORDING_DOCKER_IMAGE .